services:
  ibmmq:
    image: icr.io/ibm-messaging/mq:latest
    platform: linux/amd64
    container_name: ibmmq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: AUTORIZA
      MQ_APP_PASSWORD: passw0rd
      MQ_ADMIN_PASSWORD: admin123
    ports:
      - "1414:1414"
      - "9443:9443"
    volumes:
      - mqdata:/mnt/mqm
      - ./mq-config.mqsc:/etc/mqm/mq-config.mqsc
    healthcheck:
      test: ["CMD-SHELL", "dspmq -o status -m AUTORIZA | grep -q RUNNING"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      MQ_QMGR_NAME: AUTORIZA
      MQ_HOST: ibmmq
      MQ_PORT: "1414"
      MQ_QUEUE: BOFTD_ENV
      MQ_CHANNEL: DEV.APP.SVRCONN
      MQ_USER: app
      MQ_PASSWORD: passw0rd
      SEND_MODE: file
    depends_on:
      ibmmq:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./data.json:/app/data.json:ro

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      MQ_QMGR_NAME: AUTORIZA
      MQ_HOST: ibmmq
      MQ_PORT: "1414"
      MQ_QUEUE: BOFTD_ENV
      MQ_CHANNEL: DEV.APP.SVRCONN
      MQ_USER: app
      MQ_PASSWORD: passw0rd
    depends_on:
      ibmmq:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "mq_consumer.py"]

  

volumes:
  mqdata:
